const teamInfo = [
  {
    id: '101',
    header: 'Head of the department & Staff Advisor',
    members: [
      {
        id: '201',
        name: 'Dr. Michael Arock',
        image: '/radhe.jpg',
        designation: 'HOD',
        github: '',
        linkedin: '',
      },
      {
        id: '202',
        name: 'Dr.(Mrs.) S. Sangeetha',
        image: '/radhe.jpg',
        designation: 'Staff Advisor',
        github: '',
        linkedin: '',
      },
    ],
  },
  {
    id: '102',
    header: 'Central Execution Committee',
    members: [
      {
        id: '301',
        name: 'Abhiusnees Nandi',
        image: '/radhe.jpg',
        designation: 'Secretary',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '302',
        name: 'Pawan Agarwal',
        image: '/radhe.jpg',
        designation: 'Treasurer',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '303',
        name: 'Chirag Agarwal',
        image: '/radhe.jpg',
        designation: 'PPC Head',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '304',
        name: 'Aman Kumar Singh',
        image: '/radhe.jpg',
        designation: 'PRC Head',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '305',
        name: 'Mokshda Dave',
        image: '/radhe.jpg',
        designation: 'EEC Head',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '306',
        name: 'Chakshu Verma',
        image: '/radhe.jpg',
        designation: 'EEC Head',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '307',
        name: 'Nandini Kumari',
        image: '/radhe.jpg',
        designation: 'ARC Head',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '308',
        name: 'Tushar Nanda',
        image: '/radhe.jpg',
        designation: 'HRC Head',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
      {
        id: '309',
        name: 'Harsha Jha',
        image: '/radhe.jpg',
        designation: 'HRC Head',
        github: 'https://www.github.com',
        linkedin: 'https://w',
      },
    ],
  },
];

export default teamInfo;
