const teamInfo = [
  {
    id: '1010',
    header: 'Head of the department & Staff Advisor',
    members: [
      {
        id: '201',
        name: 'Dr. Michael Arock',
        image: '/michael-sir.jpg',
        designation: 'HOD',
        github: '',
        linkedin: '',
        message: `In the ever-accelerating currents of change, one unwavering truth remains - "Satyameva Jayate" (Truth Alone Triumphs). This mantra echoes through the corridors of the Department of Computer Applications at the National Institute of Technology (NIT) Tiruchirappalli, encapsulating our commitment to the pursuit of truth, knowledge, and technological excellence. As we stand on the precipice of the unknown, we draw inspiration from this timeless motto to invite you to the 31st edition of our prestigious annual technological festival - “Version”, the All India MCA Meet. Scheduled to unfold on 21st March, this year's edition carries a theme that resonates with the cutting edge of technology - "Generative AI." It's an exploration of the limitless possibilities and the transformative impact of Artificial Intelligence. Our students at the Department of Computer Applications are enthusiastic about delving into the realms of Generative AI, pushing the boundaries of what's achievable and inspiring the next wave of technological innovation. Version 2024, themed around Generative AI, promises a convergence of technical brilliance and creative flair. From competitions challenging the intellect to non-technical events providing a refreshing break, this annual meet is designed to showcase the incredible potential of Generative AI. Guest lectures by industry experts, networking opportunities, and an exploration of the unknown are integral parts of this event. As we reflect on the growth of Version since its inception in 1991, we're excited to witness the overwhelming participation and support from institutions, making this edition even more impactful. The myriad of events themed around Generative AI aims to propel our understanding of technology forward and bridge the gap between imagination and realization. Looking forward to a resounding success, Version 2024 promises to be a celebration of truth, knowledge, and the transformative power of Generative AI.`,
      },
      {
        id: '202',
        name: 'Dr.(Mrs.) S. Sangeetha',
        image: '/sangeetha-mam.jpg',
        designation: 'Staff Advisor',
        github: '',
        linkedin: '',
        message: `Every technological leap begins with a spark of innovation, and as we gather for the 31st edition of Version - All India MCA Meet, themed 'GENSYNTH: Synthesized Brilliance of Gen-AI,' we are not just celebrating an event but a legacy of knowledge, innovation, and progress. It is with great pleasure that I extend this heartfelt invitation to all for an extraordinary convergence of intellect and creativity organized by the Department of Computer Applications at NIT Tiruchirappalli. The theme, "GENSYNTH: Synthesized Brilliance of Gen-AI," reflects the cutting-edge exploration and innovative spirit that have become synonymous with our Department of Computer Applications at NIT Tiruchirappalli. It is heartening to witness the dedication and enthusiasm displayed by our students, as they continue to uphold the rich tradition of this event. Over the years, Version has evolved into a beacon of knowledge exchange, innovation, and technological prowess. It stands as a testament to the legacy of our department and the commitment of each organizing committee to surpass the benchmarks set by their predecessors. Version 2024 promises to be a continuation of this tradition, exploring the limitless possibilities within the realm of Generative Artificial Intelligence. As we embark on this exciting journey, I express my sincere appreciation to the organizing team. Their passion, hard work, and collaborative spirit have played a pivotal role in shaping Version, a tradition that spans 30 years of excellence. Their commitment to making this event a grand success is truly commendable and echoes the enduring legacy that our department proudly upholds. I extend a warm invitation to students from colleges nationwide to join us at Version 2024. Additionally, we are reaching out to our esteemed alumni of NIT Tiruchirappalli's MCA program, urging them to partake in this celebration of knowledge and innovation. This event is an unparalleled opportunity for the community to connect, collaborate, and share insights. Let us collectively foster an environment of learning, camaraderie, and the limitless possibilities that lie ahead. Looking forward to the active participation of students from colleges across the country, making this edition a resounding success`,
      },
    ],
  },

  {
    id: '10200',
    header: 'Central Coordination Committee',
    members: [
      {
        id: '300',
        name: 'Abhilash Singh',
        image: '/abhilash.jpg',
        designation: 'Chairperson',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },

  {
    id: '102',
    header: '',
    members: [
      {
        id: '301',
        name: 'Abhiusnees Nandi',
        image: '/abhiusnis.jpg',
        designation: 'Secretary',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '302',
        name: 'Pawan Agarwal',
        image: '/pawan.jpeg',
        designation: 'Treasurer',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '306',
        name: 'Chakshu Verma',
        image: '/chakshu.jpg',
        designation: 'EEC Head',
        github: 'https://github.com/ChakshuVerma',
        linkedin: 'https://www.linkedin.com/in/chakshu-verma-6123411bb/',
      },
      {
        id: '303',
        name: 'Chirag Agarwal',
        image: '/chirag.jpg',
        designation: 'PPC Head',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '304',
        name: 'Aman Kumar Singh',
        image: '/aman.jpg',
        designation: 'PRC Head',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },

      {
        id: '307',
        name: 'Nandini Kumari',
        image: '/nandini.jpg',
        designation: 'ARC Head',
        github: 'https://github.com/nandinisahu99',
        linkedin: 'https://www.linkedin.com/in/nandini-sahu-118a40225/',
      },
      {
        id: '308',
        name: 'Tushar Nanda',
        image: '/tushar.jpg',
        designation: 'HRC Head',
        github: 'https://github.com/tushar-nanda',
        linkedin: 'https://www.linkedin.com/in/tushar-nanda-25a466196',
      },
      {
        id: '309',
        name: 'Harsha Jha',
        image: '/harsha.jpg',
        designation: 'HRC Head',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '10100',
    header: 'Event Execution Committee',
    members: [
      {
        id: '400',
        name: 'Aayush Gupta',
        image: '/aayush_senior.jpg',
        designation: 'Chairperson',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '10101',
    header: '',
    members: [
      {
        id: '416',
        name: 'Chakshu Verma',
        image: '/chakshu.jpg',
        designation: 'EEC Head',
        github: 'https://github.com/ChakshuVerma',
        linkedin: 'https://www.linkedin.com/in/chakshu-verma-6123411bb/',
      },
    ],
  },
  {
    id: '103',
    header: '',
    members: [
      {
        id: '401',
        name: 'Anuj Sharma',
        image: '/anuj.jpeg',
        designation: '',
        github: 'https://github.com/sanuj21',
        linkedin: 'https://www.linkedin.com/in/sanuj21',
      },
      {
        id: '402',
        name: 'Rishabh Jain',
        image: '/rishabh.jpg',
        designation: '',
        github: 'https://github.com/rishabh1128',
        linkedin: 'https://www.linkedin.com/in/rishabh-jain-067303199/',
      },
      {
        id: '403',
        name: 'Manvendra Singh',
        image: '/manvendra.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/in/manvendrasingh43',
      },
      {
        id: '404',
        name: 'Suraj Soren',
        image: '/suraj.jpeg',
        designation: '',
        github: 'https://github.com/2002suraj456/',
        linkedin: 'https://www.linkedin.com/in/suraj-soren-22476b248/',
      },
      {
        id: '405',
        name: 'Prasanjeet Karmakar',
        image: '/prasanjeet.jpg',
        designation: '',
        github: 'https://github.com/Prasanjeet-Karmakar',
        linkedin: 'https://www.linkedin.com/in/prasanjeet-karmakar-783067211/',
      },
      {
        id: '406',
        name: 'Ritabrata Biswas',
        image: '/rito.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '407',
        name: 'Prince Kumar',
        image: '/prince.jpg',
        designation: '',
        github: 'https://github.com/prince385',
        linkedin: 'https://www.linkedin.com/in/prince-kumar-2a14a8157/',
      },
      {
        id: '408',
        name: 'Aachal Dhote',
        image: '/aachal.jpg',
        designation: '',
        github: 'https://github.com/aachald001',
        linkedin: 'https://www.linkedin.com/in/aachal-dhote-a7b53b244/',
      },
      {
        id: '409',
        name: 'Abhishek Rathore',
        image: '/abhishek.jpg',
        designation: '',
        github: 'https://github.com/hackcrac',
        linkedin: 'https://www.linkedin.com/in/abhishek-rathore-1bb6a4254',
      },
      {
        id: '410',
        name: 'Gurdeep Singh',
        image: '/gurdeep.jpg',
        designation: '',
        github: 'https://github.com/gurdeep2001',
        linkedin: 'https://www.linkedin.com/in/gurdeep-singh-159a23219/',
      },
      {
        id: '411',
        name: 'Raj Sen',
        image: '/raj.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '412',
        name: 'Aayush Gupta',
        image: '/aayush.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/in/aayush-g-b41272187',
      },
      {
        id: '413',
        name: 'Lokesh Verma',
        image: '/lokesh.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '414',
        name: 'Naman Jain',
        image: '/naman.jpg',
        designation: '',
        github: 'https://github.com/namannjk',
        linkedin: 'https://www.linkedin.com/in/naman-jain-9794b61b8',
      },
      {
        id: '415',
        name: 'Shivam',
        image: '/shivam.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '417',
        name: 'Sachin Kumar',
        image: '/sachin.JPG',
        designation: '',
        github: 'https://github.com/Sachin-Kushwaha1',
        linkedin: 'https://www.linkedin.com/in/sachin-kumar-a7110a183/',
      },
    ],
  },
  {
    id: '10300',
    header: 'Public Relations Committee',
    members: [
      {
        id: '509',
        name: 'Ashay Jain',
        image: '/ashay.jpg',
        designation: 'Chairperson',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '10301',
    header: '',
    members: [
      {
        id: '500',
        name: 'Aman Kumar Singh',
        image: '/aman.jpg',
        designation: 'PRC Head',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '104',
    header: '',
    members: [
      {
        id: '501',
        name: 'Diwanshu Kumar',
        image: '/diwanshu.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '502',
        name: 'Nitika Verma',
        image: '/nitika.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/in/nitika-verma-9210a51aa/',
      },
      {
        id: '503',
        name: 'Balasainath',
        image: '/bala.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '504',
        name: 'Radhesham Ambhure',
        image: '/radhe1.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '505',
        name: 'Ritik Nayak',
        image: '/ritik.jpeg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'http://linkedin.com/in/ritik-nayak-865626248',
      },
      {
        id: '506',
        name: 'Parab Satyaranjan',
        image: '/parab.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin:
          'https://www.linkedin.com/in/parab-satyaranjan-munda-6956b6248/',
      },
      {
        id: '507',
        name: 'Achintya Raj',
        image: '/achintya.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '508',
        name: 'Pallavi Priya',
        image: '/pallavi.jpeg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '510',
        name: 'Shivaraj G',
        image: '/shivaraj.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/in/shiva-raj-ab2145283/',
      },
    ],
  },
  {
    id: '10400',
    header: 'Alumni Relations Committee',
    members: [
      {
        id: '607',
        name: 'Akash Dave',
        image: '/akash.jpg',
        designation: 'Chairperson',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '10401',
    header: '',
    members: [
      {
        id: '600',
        name: 'Nandini Kumari',
        image: '/nandini.jpg',
        designation: 'ARC Head',
        github: 'https://github.com/nandinisahu99',
        linkedin: 'https://www.linkedin.com/in/nandini-sahu-118a40225/',
      },
    ],
  },
  {
    id: '105',
    header: '',
    members: [
      {
        id: '601',
        name: 'Shubhi Gupta',
        image: '/shubhi.jpg',
        designation: '',
        github: 'https://github.com/Shubhi2901',
        linkedin: 'https://www.linkedin.com/in/shubhi-gupta-4866301b6/',
      },
      {
        id: '602',
        name: 'Jayshree Raghuvanshi',
        image: '/jayshree.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '603',
        name: 'Ruchi Singh',
        image: '/ruchi.jpg',
        designation: '',
        github: 'https://github.com/085-ruchi',
        linkedin: 'http://www.linkedin.com/in/ruchi-singh-850a3924b',
      },
      {
        id: '604',
        name: 'Akanksha Singh',
        image: '/akanksha.jpg',
        designation: '',
        github: 'https://github.com/008-Akanksha/Akanksha-Singh',
        linkedin: 'https://www.linkedin.com/in/akanksha-singh-9a637b24a/',
      },
      {
        id: '605',
        name: 'Utkarsh Sharma',
        image: '/utkarsh.jpg',
        designation: '',
        github: 'https://github.com/utkarsharma18',
        linkedin: 'https://www.linkedin.com/in/utkarsh-sharma-389992247/',
      },
      {
        id: '606',
        name: 'Deepak Reswal',
        image: '/deepak-reswal.jpg',
        designation: '',
        github: 'https://github.com/deepakreswal021',
        linkedin: 'http://www.linkedin.com/in/deepak-reswal-1139b8253',
      },
      {
        id: '608',
        name: 'Himanshu Gupta',
        image: '/himanshu-gupta.jpg',
        designation: '',
        github: 'https://github.com/032himanshugupta',
        linkedin: 'https://www.linkedin.com/in/himanshu-gupta-94247a155/',
      },
      {
        id: '609',
        name: 'Nikhil Patel',
        image: '/nikhil-patel.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin:
          'https://www.linkedin.com/in/nikhil-patel-b1868624b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app',
      },
      {
        id: '610',
        name: 'Ronit Raj Bairwa',
        image: '/ronit.png',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'http://www.linkedin.com/in/ronit-raj-bairwa-531759248',
      },
      {
        id: '611',
        name: 'Nikhil Choudhary',
        image: '/nikhil-choudhary.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'http://www.linkedin.com/',
      },
      {
        id: '612',
        name: 'Khushi Desai',
        image: '/khushi.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'http://www.linkedin.com/in/khushi-desai-4a94bb22a',
      },
    ],
  },
  {
    id: '10500',
    header: 'Hospitality and Reception Committee',
    members: [
      {
        id: '709',
        name: 'Sumit Kushwaha',
        image: '/sumit.jpg',
        designation: 'Chairperson',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '1050',
    header: '',
    members: [
      {
        id: '700',
        name: 'Tushar Nanda',
        image: '/tushar.jpg',
        designation: 'HRC Head',
        github: 'https://github.com/tushar-nanda',
        linkedin: 'https://www.linkedin.com/in/tushar-nanda-25a466196',
      },
      {
        id: '701',
        name: 'Harsha Jha',
        image: '/harsha.jpg',
        designation: 'HRC Head',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '106',
    header: '',
    members: [
      {
        id: '703',
        name: 'Shivani Gattani',
        image: '/shivani.jpg',
        designation: '',
        github: 'https://github.com/091-shivani',
        linkedin: 'https://www.linkedin.com/in/shivani-gattani-a263a5264',
      },
      {
        id: '704',
        name: 'Pushkar Srivastav',
        image: '/pushkar.jpg',
        designation: '',
        github: 'https://github.com/070Pushkar',
        linkedin: 'https://www.linkedin.com/in/pushkar-srivastav-85905b244/',
      },
      {
        id: '705',
        name: 'Rakesh Kumar',
        image: '/rakesh.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '706',
        name: 'Mithilesh Kumar',
        image: '/mithilesh.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/in/mithilesh-kumar-978a98249/',
      },
      {
        id: '707',
        name: 'Vikash Patel',
        image: '/vikas.jpeg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '708',
        name: 'Gaurav Sawasiya',
        image: '/gaurav.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '710',
        name: 'Rajesh',
        image: '/rajesh.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '10600',
    header: 'Printing and Publishing Committee',
    members: [
      {
        id: '808',
        name: 'Somesh Harsule',
        image: '/somesh.jpg',
        designation: 'Chairperson',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '10601',
    header: '',
    members: [
      {
        id: '800',
        name: 'Chirag Agarwal',
        image: '/chirag.jpg',
        designation: 'PPC Head',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
  {
    id: '107',
    header: '',
    members: [
      {
        id: '801',
        name: 'Ashish Yogi',
        image: '/ashish.png',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '802',
        name: 'P. Janardhan',
        image: '/janardhan.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '803',
        name: 'Aryan Gogia',
        image: '/aryan.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '804',
        name: 'Vivek Pandey',
        image: '/vivek.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '805',
        name: 'Sudhir Kumar',
        image: '/sudhir.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '806',
        name: 'Himanshu Upadhyay',
        image: '/himanshu-upadhyay.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
      {
        id: '807',
        name: 'Surandra Meena',
        image: '/surandra.jpg',
        designation: '',
        github: 'https://github.com/',
        linkedin: 'https://www.linkedin.com/',
      },
    ],
  },
];

export default teamInfo;
